from _support import ref
from cmf_pipeline.application import PipelineApplication
from cmf_pipeline.media import FFmpegSourceLedRenderer,RenderedVideoEvaluator,RemotionBindingCompiler,HyperFramesBindingCompiler

def test_ffmpeg_source_led_render(source_video,tmp_path):
 app=PipelineApplication(tmp_path/'db.sqlite3');app.initialize()
 reg=app.source_media.register(source_path=source_video,logical_uri='media/source.mp4',source_package_ref=ref('source-pkg','a'),transcript_alignment_ref=ref('transcript','b'),visual_index_ref=ref('visual','c'),restrictions=['operator'],idempotency_key='reg')['object']['payload']
 words=[{'word_id':'w1','text':'A','start_ms':100,'end_ms':800,'speaker_id':'g','protected_tail_ms':0},{'word_id':'w2','text':'B','start_ms':1200,'end_ms':2200,'speaker_id':'g','protected_tail_ms':0}]
 edl=app.edls.compile(source_registration_ref=ref(reg['registration_id'],'r'),expression_moment_ref=ref('moment','m'),words=words,selections=[{'selection_id':'a','start_word_id':'w1','end_word_id':'w1','function':'HOOK','cut_in_class':'WORD_BOUNDARY','cut_out_class':'WORD_BOUNDARY','authorized_reorder':False},{'selection_id':'b','start_word_id':'w2','end_word_id':'w2','function':'CLAIM','cut_in_class':'WORD_BOUNDARY','cut_out_class':'WORD_BOUNDARY','authorized_reorder':False}],allow_reorder=False,idempotency_key='edl')['object']['payload']
 duration=edl['output_duration_ms'];req={'derivative_job_ref':ref('job','j'),'source_registration_ref':ref(reg['registration_id'],'r'),'semantic_production_package_ref':ref('semantic','x'),'final_script_ref':ref('script','x'),'activation_transfer_contract_ref':ref('transfer','x'),'harness_binding_ref':ref('binding','x'),'canvas':{'width':360,'height':640,'fps_numerator':30,'fps_denominator':1,'duration_ms':duration},'timebase':{'numerator':1,'denominator':1000},'tracks':[{'track_id':'v','track_type':'VIDEO','role':'PRIMARY_A_ROLL_SPINE','z_index':0,'elements':[{'element_id':f'e{i}','kind':'SOURCE_SEGMENT','output_start_ms':e['output_start_ms'],'output_end_ms':e['output_end_ms'],'semantic_role':'SOURCE','sequence_role':e['function'],'source_registration_ref':ref(reg['registration_id'],'r'),'source_start_ms':e['source_start_ms'],'source_end_ms':e['source_end_ms'],'artifact_ref':'NOT_APPLICABLE','generated_slot_state':'NOT_APPLICABLE','bbox_intent_ref':'NOT_APPLICABLE','text':'NOT_APPLICABLE'} for i,e in enumerate(edl['entries'])]}],'evaluation_profile_ref':ref('eval','x'),'wrong_reading_locks':['keep_source']}
 program=app.video_programs.compile(req,idempotency_key='p')['object']['payload'];render=FFmpegSourceLedRenderer().render(source_path=source_video,edl=edl,output_dir=tmp_path/'out',logical_output_uri='video/out.mp4');assert (tmp_path/'out/out.mp4').is_file();artifact_ref={'object_id':render['manifest']['artifact_id'],'version':'1.0.0','sha256':render['manifest']['sha256']};evaluation=RenderedVideoEvaluator().evaluate(artifact_path=render['output_path'],artifact_ref=artifact_ref,program=program,edl=edl,producer_actor_id='producer',evaluator_actor_id='evaluator',evidence_dir=tmp_path/'evidence');assert evaluation['verdict'].startswith('PASS');assert len(evaluation['cut_evidence'])==1
 rem=RemotionBindingCompiler().compile(program=program,composition_id='Main',runtime_ref=ref('remotion','r'));hyp=HyperFramesBindingCompiler().compile(program=program,block_registry_ref=ref('blocks','b'),block_ids=['claim']);assert rem['canonical_source']=='VideoEditProgram';assert hyp['runtime_execution_authorized'] is False
