from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from ca_contracts import canonical_sha256

from ..repositories.air_repository import AirRepository
from .production_common import add_lineage_edges, stored_result_ref

BRANCH_CONDITIONS=("ANCHOR_HIT","PARTIAL_HIT","DEFENSE","TOPIC_ESCAPE","CONTRADICTION","OVERLOAD","RELATIONAL_RESET")


class Phase9ActivativeService:
    def __init__(self, repository: AirRepository):
        self.repository=repository

    def _store(self, object_type: str, payload: Mapping[str,Any], *, key: str, expected_revision: int|None=None) -> dict[str,Any]:
        from ..domain import validate_air_object
        normalized=validate_air_object(object_type,payload)
        result=self.repository.store_object(object_type,normalized,idempotency_key=key,expected_revision=expected_revision)
        refs=[]
        for name,value in normalized.items():
            if name.endswith("_ref") and isinstance(value,Mapping) and set(value)>={"object_id","version","sha256"}: refs.append(value)
            if name.endswith("_refs") and isinstance(value,Sequence) and not isinstance(value,(str,bytes,bytearray)):
                refs.extend(item for item in value if isinstance(item,Mapping) and set(item)>={"object_id","version","sha256"})
        if refs:
            add_lineage_edges(self.repository,source_result=result,relation_type=f"{object_type}:depends_on",target_refs=refs,evidence={"compiler":"phase9-activative-service"})
        return result

    def compile_interview_asset_contract(self, *, program_id: str, planned_pack_ref: Mapping[str,Any], source_context_ref: Mapping[str,Any], evidence_refs: Sequence[Mapping[str,Any]], parent_lock_refs: Sequence[Mapping[str,Any]], evaluation_profile_ref: Mapping[str,Any], idempotency_key: str) -> dict[str,Any]:
        branch_actions={
            "ANCHOR_HIT":("CLARIFY",0,"Ask one bounded clarifier that preserves the landed truth."),
            "PARTIAL_HIT":("CLARIFY",0,"Clarify the missing specificity without restarting the induction."),
            "DEFENSE":("LOWER_PRESSURE",-1,"Name the protective pattern without diagnosing identity and offer choice."),
            "TOPIC_ESCAPE":("REFLECT",0,"Reflect the shift and ask whether to return or stop."),
            "CONTRADICTION":("REFLECT",0,"Name the contradiction in the statement and leave resolution to the guest."),
            "OVERLOAD":("PAUSE",-2,"Pause, reduce scope, or terminate; do not treat distress as productive depth."),
            "RELATIONAL_RESET":("RELATIONAL_RESET",-1,"Restore the shared field and continue only with explicit consent."),
        }
        branches=[]
        for condition in BRANCH_CONDITIONS:
            action,delta,text=branch_actions[condition]
            branches.append({"condition":condition,"action_kind":action,"question_or_action":text,"pressure_delta":delta,"maximum_uses":1,"recovery_ref":dict(evidence_refs[0]),"landing_effect":"Preserve honest release or stop.","stop_effect":"Stop when evidence or consent is insufficient.","operator_choice_required":condition in {"DEFENSE","OVERLOAD","RELATIONAL_RESET"}})
        payload={
            "program_id":program_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"validated","epistemic_state":"planned",
            "planned_pack_ref":dict(planned_pack_ref),"source_context_ref":dict(source_context_ref),
            "target_expression_state":{"current_hypothesis":"The source protects agency through control.","desired_movement":"The guest can locate the cost of control without being told what to feel.","observable_transition_signals":["specific example","self-authored revision","owned consequence"],"inappropriate_conditions":["overload","withdrawn consent","identity attack"],"relationship_requirements":["dignity","choice","clear stop route"],"pressure_ceiling":3,"evidence_refs":[dict(x) for x in evidence_refs]},
            "first_line_anchor":{"anchor_id":f"{program_id}:first-line","text":"When did control stop helping?","primitive_ref":dict(evidence_refs[0]),"evidence_refs":[dict(x) for x in evidence_refs],"claim_limit":"Supported premise only; no fabricated disruption."},
            "depth_anchor":{"anchor_id":f"{program_id}:depth","text":"What did that look like in one real moment?","primitive_ref":dict(evidence_refs[-1]),"evidence_refs":[dict(x) for x in evidence_refs],"claim_limit":"Request lived specificity without prescribing truth."},
            "branch_program":branches,"pressure_envelope":{"initial_dose":1,"ceiling":3,"reset_dose":0,"stop_conditions":["consent withdrawn","overload evidence","source contradiction unresolved"]},
            "landing_criteria":{"honest_release_required":True,"allowed_outcomes":["meaning","decision","question","stop"],"fabricated_success_forbidden":True},
            "route_hypotheses":[{"route_id":f"{program_id}:route:source-led-short","state":"PLANNED_UNCONFIRMED","required_expression_evidence_refs":[dict(x) for x in evidence_refs],"source_requirements":["complete premise","reaction tail"]}],
            "parent_lock_refs":[dict(x) for x in parent_lock_refs],"evaluation_profile_ref":dict(evaluation_profile_ref),"limitations":["planned_only","human_must_arm","live_evidence_owned_by_interview_expression"]}
        return self._store("interview_asset_contract",payload,key=idempotency_key)

    def arm_contract(self, *, receipt_id: str, contract_ref: Mapping[str,Any], session_context_ref: Mapping[str,Any], compiler_actor_id: str, evaluator_actor_id: str, human_actor_id: str, idempotency_key: str) -> dict[str,Any]:
        payload={"receipt_id":receipt_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"armed_development","contract_ref":dict(contract_ref),"evaluation_result":"PASS","compiler_actor_id":compiler_actor_id,"evaluator_actor_id":evaluator_actor_id,"human_actor_id":human_actor_id,"session_context_ref":dict(session_context_ref),"armed_hashes":[contract_ref["sha256"],session_context_ref["sha256"]],"production_authorized":False}
        return self._store("interview_asset_contract_arm_receipt",payload,key=idempotency_key)

    def compile_live_policy(self, *, proposal_id: str, contract_ref: Mapping[str,Any], live_state_ref: Mapping[str,Any], evidence_refs: Sequence[Mapping[str,Any]], current_dose: int, ceiling: int, overload: bool, producer_actor_id: str, evaluator_actor_id: str, idempotency_key: str) -> dict[str,Any]:
        if overload:
            recommended=max(0,current_dose-1); call_text="Pause and decide whether to reset, land, or stop."; action="PAUSE"; eligible=True
        else:
            recommended=min(current_dose+1,ceiling); call_text="What changed when control stopped helping?"; action="CLARIFY"; eligible=True
        calls=[{"call_id":f"{proposal_id}:call:primary","text":call_text,"action_kind":action,"pressure_dose":recommended,"expected_transition":"specific source-backed expression or an explicit stop","stop_conditions":["overload","consent withdrawn","no evidence"],"eligible":eligible,"reason_codes":["SMALLEST_USEFUL_CALL"]},{"call_id":f"{proposal_id}:call:stop","text":"We can stop here.","action_kind":"STOP","pressure_dose":0,"expected_transition":"terminal stop","stop_conditions":["operator chooses stop"],"eligible":True,"reason_codes":["ALWAYS_AVAILABLE_STOP"]}]
        payload={"proposal_id":proposal_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"proposed","epistemic_state":"inferred","interview_asset_contract_ref":dict(contract_ref),"live_state_ref":dict(live_state_ref),"state_watermark":canonical_sha256({"live_state_ref":live_state_ref,"current_dose":current_dose}),"counteractivation_profile":{"hypotheses":["possible defense","possible overload" if overload else "possible partial hit"],"evidence_refs":[dict(x) for x in evidence_refs],"counterevidence_refs":[],"limitations":["does not diagnose person or motive"],"maximum_claim":"bounded policy hypothesis only"},"call_options":calls,"pressure_recommendation":{"current_dose":current_dose,"recommended_dose":recommended,"ceiling":ceiling,"expected_gain_micros":300000 if not overload else 50000,"overload_risk_micros":850000 if overload else 150000,"reset_route":"PAUSE_OR_LAND","evidence_refs":[dict(x) for x in evidence_refs]},"transition_options":[{"kind":"DELIVER_CALL","call_id":calls[0]["call_id"]},{"kind":"STOP","call_id":calls[1]["call_id"]}],"smallest_useful_call_proof":{"selected_call_id":calls[0]["call_id"],"dominates_call_ids":[],"reason_codes":["LOWEST_PRESSURE_WITH_EXPECTED_INFORMATION_GAIN"],"incomparable":False},"producer_actor_id":producer_actor_id,"evaluator_actor_id":evaluator_actor_id,"limitations":["proposal_only","interview_expression_owns_delivery_and_reaction"]}
        return self._store("live_narrative_policy_proposal",payload,key=idempotency_key)

    def compile_observed_pack(self, *, pack_id: str, source_package_refs: Sequence[Mapping[str,Any]], reaction_refs: Sequence[Mapping[str,Any]], expression_refs: Sequence[Mapping[str,Any]], input_manifest_ref: Mapping[str,Any], candidate_portfolio_ref: Mapping[str,Any], independent_evaluation_ref: Mapping[str,Any], human_resolution_ref: Mapping[str,Any], planned_pack_ref: Mapping[str,Any]|None, idempotency_key: str) -> dict[str,Any]:
        claims=[{"claim_id":f"{pack_id}:claim:role","field":"actual_psychological_role","value":"self-recognizing witness","epistemic_state":"inferred","evidence_refs":[dict(x) for x in expression_refs],"limitations":["role is interpreted from approved evidence"],"maximum_claim":"campaign/source scoped"},{"claim_id":f"{pack_id}:claim:direction","field":"actual_activation_direction","value":"MIRROR","epistemic_state":"inferred","evidence_refs":[dict(x) for x in reaction_refs],"limitations":["not a personality diagnosis"],"maximum_claim":"source scoped"}]
        delta=[] if planned_pack_ref is None else [{"field":"psychological_role","planned_ref":dict(planned_pack_ref),"observed_value":"self-recognizing witness","interpretation":"supported_with_limitations"}]
        payload={"pack_id":pack_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"published_development","epistemic_state":"observed","source_package_refs":[dict(x) for x in source_package_refs],"reaction_receipt_refs":[dict(x) for x in reaction_refs],"expression_moment_refs":[dict(x) for x in expression_refs],"input_manifest_ref":dict(input_manifest_ref),"semantic_claims":claims,"primitive_evidence":[],"planned_observed_delta":delta,"negative_and_unresolved_evidence":[{"kind":"UNRESOLVED","statement":"Audience response remains unknown before publication."}],"candidate_portfolio_ref":dict(candidate_portfolio_ref),"independent_evaluation_ref":dict(independent_evaluation_ref),"human_resolution_ref":dict(human_resolution_ref),"downstream_consumers":["atomic-harness-pipeline","conscious-activations-studio"],"limitations":["not production certified","source evidence remains owned by interview expression"]}
        return self._store("observed_activative_intelligence_pack",payload,key=idempotency_key)

    def compile_freshness_profile(self, *, profile_id: str, audience_context_ref: Mapping[str,Any], platform_profile_id: str, exposure_refs: Sequence[Mapping[str,Any]], role_counts: Mapping[str,int], idempotency_key: str) -> dict[str,Any]:
        gates=[{"gate_id":"role-repetition","result":"FAIL" if max(role_counts.values(),default=0)>2 else "PASS","threshold":2},{"gate_id":"relief-deficit","result":"PASS","threshold":1}]
        findings=[{"kind":"FRESH" if all(g["result"]=="PASS" for g in gates) else "FATIGUE_RISK","evidence":"exact audience-context repetition counts","epistemic_state":"inferred"}]
        payload={"profile_id":profile_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"validated","epistemic_state":"inferred","audience_context_ref":dict(audience_context_ref),"platform_profile_id":platform_profile_id,"window":{"start_utc":"2026-01-01T00:00:00Z","end_utc":"2026-12-31T23:59:59Z","measurement_definition":"development reference exposure window"},"exposure_refs":[dict(x) for x in exposure_refs],"repetition_counts":dict(sorted(role_counts.items())),"hard_gates":gates,"freshness_findings":findings,"limitations":["no causal audience claim","no platform production telemetry"]}
        return self._store("activation_freshness_profile",payload,key=idempotency_key)

    def compile_campaign(self, *, program_id: str, audience_context_ref: Mapping[str,Any], campaign_policy_ref: Mapping[str,Any], freshness_profile_ref: Mapping[str,Any], derivative_program_refs: Sequence[Mapping[str,Any]], tension_ref: Mapping[str,Any], edge_ref: Mapping[str,Any], coalition_ref: Mapping[str,Any], archetype_ref: Mapping[str,Any], wrong_reading_lock_refs: Sequence[Mapping[str,Any]], evaluation_profile_ref: Mapping[str,Any], idempotency_key: str) -> dict[str,Any]:
        roles=("self-recognizing witness","accountable chooser","protective skeptic","participant")
        plans=[]
        for idx,ref in enumerate(derivative_program_refs):
            plans.append({"asset_plan_id":f"{program_id}:asset:{idx}","sequence_index":idx,"derivative_program_ref":dict(ref),"psychological_role":roles[idx%len(roles)],"tension_ref":dict(tension_ref),"activation_direction":("MIRROR","TARGET","CONTRADICTION","PARTICIPATION")[idx%4],"edge_product_ref":dict(edge_ref),"primitive_coalition_ref":dict(coalition_ref),"archetype_coalition_ref":dict(archetype_ref),"format_profile_id":("format07_direct_coaching_a_roll","supervisual_reference","carousel_reference","animation_scene_reference")[idx%4],"pressure_class":("LOW","MEDIUM","MEDIUM","LOW")[idx%4],"relief_class":("NONE","PARTIAL","FULL","AFFINITY_RESET")[idx%4],"publication_function":("HOOK","PROOF","DEEPEN","PARTICIPATION")[idx%4]})
        payload={"program_id":program_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"evaluated_development","epistemic_state":"planned","audience_context_ref":dict(audience_context_ref),"campaign_policy_ref":dict(campaign_policy_ref),"asset_plans":plans,"freshness_profile_ref":dict(freshness_profile_ref),"wrong_reading_lock_refs":[dict(x) for x in wrong_reading_lock_refs],"evaluation_profile_ref":dict(evaluation_profile_ref),"limitations":["semantic campaign only","pipeline owns operational schedule"]}
        return self._store("campaign_activation_program",payload,key=idempotency_key)

    def record_audience_reaction(self, *, receipt_id: str, campaign_ref: Mapping[str,Any], asset_ref: Mapping[str,Any], producer_actor_id: str, evaluator_actor_id: str, idempotency_key: str) -> dict[str,Any]:
        payload={"receipt_id":receipt_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"recorded_development","epistemic_state":"observed","campaign_program_ref":dict(campaign_ref),"asset_ref":dict(asset_ref),"platform_profile_id":"development_export","observation_window":{"start_utc":"2026-01-01T00:00:00Z","end_utc":"2026-01-02T00:00:00Z"},"observed_metrics":[{"metric":"operator_review_acceptance","numerator":1,"denominator":1,"definition_version":"1.0"}],"measurement_limits":["not platform telemetry","single development operator review"],"inferred_role_signals":[{"role":"self-recognizing witness","signal":"operator accepted role/tension continuity","epistemic_state":"inferred"}],"producer_actor_id":producer_actor_id,"evaluator_actor_id":evaluator_actor_id,"limitations":["cannot rewrite source truth or semantic authority"]}
        return self._store("audience_reaction_receipt",payload,key=idempotency_key)

    def compile_relationship_program(self, *, state_id: str, subject_ref: Mapping[str,Any], evidence_refs: Sequence[Mapping[str,Any]], coalition_ref: Mapping[str,Any], evaluation_ref: Mapping[str,Any], idempotency_key: str) -> tuple[dict[str,Any],dict[str,Any]]:
        state_payload={"state_id":state_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"active_development","epistemic_state":"inferred","subject_ref":dict(subject_ref),"stage":"ENGAGED","evidence_refs":[dict(x) for x in evidence_refs],"pressure_ceiling":2,"affinity_state":"earned_recognition","previous_state_ref":"NOT_APPLICABLE","limitations":["relationship stage is evidence-scoped"]}
        state=self._store("relationship_activation_state",state_payload,key=f"{idempotency_key}:state")
        state_ref=stored_result_ref(state)
        steps=[{"step_id":"recognize","stage_from":"DISCOVERED","stage_to":"RECOGNIZED","owner_product":"activative-intelligence-runtime","entry_evidence_kinds":["PUBLIC_EXPRESSION"],"completion_evidence_kind":"RECOGNITION_RECEIPT","status":"COMPLETED"},{"step_id":"engage","stage_from":"RECOGNIZED","stage_to":"ENGAGED","owner_product":"activative-intelligence-runtime","entry_evidence_kinds":["REPLY"],"completion_evidence_kind":"RESPONSE_RECEIPT","status":"ACTIVE"},{"step_id":"brief","stage_from":"ENGAGED","stage_to":"BRIEF_ACCEPTED","owner_product":"activative-intelligence-runtime","entry_evidence_kinds":["CONFIRMED_INTEREST"],"completion_evidence_kind":"BRIEF_ACCEPTANCE_RECEIPT","status":"PENDING"}]
        program_payload={"program_id":f"{state_id}:progression","version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"active_development","epistemic_state":"planned","relationship_state_ref":state_ref,"transition_policy_ref":dict(evaluation_ref),"ordered_steps":steps,"current_step_id":"engage","primitive_coalition_ref":dict(coalition_ref),"pause_reset_cancel_policy_ref":dict(evaluation_ref),"evaluation_receipt_ref":dict(evaluation_ref),"limitations":["delivery does not imply response","no automatic stage advance"]}
        program=self._store("reelcast_progression_program",program_payload,key=f"{idempotency_key}:program")
        return state,program

    def compile_visual_handoff(self, *, handoff_id: str, source_refs: Sequence[Mapping[str,Any]], semantic_package_ref: Mapping[str,Any], final_script_ref: Mapping[str,Any], transfer_ref: Mapping[str,Any], wrong_reading_locks: Sequence[Mapping[str,Any]], producer_actor_id: str, evaluator_actor_id: str, idempotency_key: str) -> dict[str,Any]:
        semantic_pack={"pack_id":f"{handoff_id}:semantic","recognition_intent":"The viewer recognizes the protective logic and its cost.","viewer_role":"self-recognizing witness","recognition_carrier":"source face, direct claim, and preserved reaction tail","source_evidence_refs":[dict(x) for x in source_refs],"wrong_reading_risks":["generic advice","stock-testimonial reading"]}
        narrative={"program_id":f"{handoff_id}:narrative","viewer_role_progression":["observer","self-recognizing witness","accountable chooser"],"beats":[{"beat_id":"recognize","visual_job":"establish human source"},{"beat_id":"pressure","visual_job":"externalize cost"},{"beat_id":"participate","visual_job":"invite smallest useful movement"}],"prediction_gap":"control looks like competence until its relational cost becomes visible","payoff":"listening can preserve agency"}
        comp=[{"composition_intent_id":f"{handoff_id}:composition:1","sequence_role":"IDENTITY_ESTABLISHMENT","semantic_hierarchy":["source_face","claim","evidence"],"reading_path":["source_face","claim"],"negative_space_intents":["right_claim_reservation"],"bbox_intents":[{"intent_id":"identity-anchor","attention_function":"identity registers before claim","relative_priority":1,"protected_absence":"right_claim_reservation"}],"wrong_reading_locks":[dict(x) for x in wrong_reading_locks]}]
        features=[{"feature_contract_id":f"{handoff_id}:feature:negative-space","feature_kind":"NEGATIVE_SPACE","semantic_job":"preserve claim reservation without shrinking identity","required_state":"right-side reservation remains readable","prohibited_states":["face-text collision"],"semantic_owner":"activative-intelligence-runtime","feasibility_owner":"visual-asset-editor","realization_owner":"visual-asset-editor"}]
        req=[{"intent_id":f"{handoff_id}:requirement:portrait","asset_family":"PORTRAIT","semantic_role":"IDENTITY_ANCHOR","sequence_role":"IDENTITY_ESTABLISHMENT","authority_class":"NONAUTHORITATIVE_REQUIREMENT_INTENT","permitted_variation":["crop","scale","background salience"],"prohibited_choices":["provider selection","model selection","workflow selection"]}]
        payload={"handoff_id":handoff_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"published_development","epistemic_state":"planned","source_package_refs":[dict(x) for x in source_refs],"semantic_production_package_ref":dict(semantic_package_ref),"approved_final_script_ref":dict(final_script_ref),"activation_transfer_contract_ref":dict(transfer_ref),"visual_semantic_pack":semantic_pack,"visual_narrative_program":narrative,"composition_intents":comp,"feature_contracts":features,"requirement_intents":req,"category_id":"short_form_edited_video","profile_id":"format07_direct_coaching_a_roll","wrong_reading_lock_refs":[dict(x) for x in wrong_reading_locks],"producer_actor_id":producer_actor_id,"evaluator_actor_id":evaluator_actor_id,"limitations":["AIR intent only","Pipeline owns Composition IR","VAE owns production strategy"]}
        return self._store("visual_activation_handoff",payload,key=idempotency_key)

    def evaluate_activation(self, *, receipt_id: str, target_ref: Mapping[str,Any], profile_ref: Mapping[str,Any], producer_actor_id: str, evaluator_actor_id: str, checks: Sequence[Mapping[str,Any]], judgments: Sequence[Mapping[str,Any]], idempotency_key: str) -> dict[str,Any]:
        hard_fail=any(c.get("hard_gate") and c.get("result")!="PASS" for c in checks)
        verdict="FAIL" if hard_fail else "PASS"
        attr="NOT_APPLICABLE" if not hard_fail else {"responsible_layer":"air.visual_semantics","reason_codes":["HARD_GATE_FAILED"],"repair_scope":"local_semantic_successor"}
        payload={"receipt_id":receipt_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"recorded_development","target_ref":dict(target_ref),"evaluation_profile_ref":dict(profile_ref),"deterministic_checks":[dict(x) for x in checks],"judgment_dimensions":[dict(x) for x in judgments],"failure_attribution":attr,"producer_actor_id":producer_actor_id,"evaluator_actor_id":evaluator_actor_id,"verdict":verdict,"limitations":["development evaluator","not certified"]}
        return self._store("activation_evaluation_receipt",payload,key=idempotency_key)


    def record_programmed_model_evidence(self, *, evidence_id: str, model_claim_ref: Mapping[str,Any], dataset_refs: Sequence[Mapping[str,Any]], evaluation_refs: Sequence[Mapping[str,Any]], shadow_ref: Mapping[str,Any], baseline_ref: Mapping[str,Any], fallback_ref: Mapping[str,Any], task_family: str, idempotency_key: str) -> dict[str,Any]:
        payload={"evidence_id":evidence_id,"version":"1.0.0","authority":{"authority_id":"ca-program-control-v2.1-candidate","authority_version":"2.1.0-candidate","authority_sha256":"a"*64,"authority_state":"candidate_not_current"},"lifecycle_state":"shadow_development","model_claim_ref":dict(model_claim_ref),"task_family":task_family,"dataset_lineage_refs":[dict(x) for x in dataset_refs],"evaluation_receipt_refs":[dict(x) for x in evaluation_refs],"shadow_result_ref":dict(shadow_ref),"baseline_comparison_ref":dict(baseline_ref),"fallback_ref":dict(fallback_ref),"applicability_envelope":{"categories":["short_form_edited_video","supervisual"],"maximum_authority":"proposal_only","requires_independent_evaluation":True},"promotion_state":"SHADOW_READY","limitations":["no live weight update","no production promotion","bounded task family only"]}
        return self._store("programmed_model_evidence",payload,key=idempotency_key)
