from __future__ import annotations

from enum import StrEnum


class AuthorityState(StrEnum):
    CURRENT = "current"
    CANDIDATE_NOT_CURRENT = "candidate_not_current"
    SUPERSEDED = "superseded"


class SourceClass(StrEnum):
    CURRENT_AUTHORITY = "CURRENT_AUTHORITY"
    CURRENT_IMPLEMENTATION = "CURRENT_IMPLEMENTATION"
    UNIQUE_EVIDENCE = "UNIQUE_EVIDENCE"
    OPTIONAL_REFERENCE = "OPTIONAL_REFERENCE"
    DEFERRED_REFERENCE = "DEFERRED_REFERENCE"
    SUPERSEDED = "SUPERSEDED"
    HISTORICAL = "HISTORICAL"


class SourceDisposition(StrEnum):
    REUSE = "REUSE"
    ADAPT = "ADAPT"
    ACTIVATE = "ACTIVATE"
    REPLACE = "REPLACE"
    ARCHIVE = "ARCHIVE"


class AdmissionDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    DENIED = "DENIED"


class HarnessState(StrEnum):
    IMPORTED = "IMPORTED"
    VERIFIED = "VERIFIED"
    RECONCILED = "RECONCILED"
    BOUND = "BOUND"
    INVALIDATED = "INVALIDATED"
    SUPERSEDED = "SUPERSEDED"


class BatchState(StrEnum):
    PROPOSED = "PROPOSED"
    COMPILED = "COMPILED"
    RUNNING = "RUNNING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INVALIDATED = "INVALIDATED"


class JobState(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INVALIDATED = "INVALIDATED"


class NodeState(StrEnum):
    BLOCKED = "BLOCKED"
    READY = "READY"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INVALIDATED = "INVALIDATED"
    QUARANTINED = "QUARANTINED"


class RunState(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INVALIDATED = "INVALIDATED"


class NodeKind(StrEnum):
    DETERMINISTIC_MODULE = "DETERMINISTIC_MODULE"
    AGENT_PROGRAM = "AGENT_PROGRAM"
    PROGRAMMED_MODEL = "PROGRAMMED_MODEL"
    HUMAN_GATE = "HUMAN_GATE"
    EXTERNAL_PRODUCT = "EXTERNAL_PRODUCT"
    RUNTIME_ADAPTER = "RUNTIME_ADAPTER"
    CONTROL = "CONTROL"


class WorkflowRole(StrEnum):
    HUNTER = "HUNTER"
    ANALYST = "ANALYST"
    COMPOSER = "COMPOSER"
    COMMANDER = "COMMANDER"
    NOT_APPLICABLE = "NOT_APPLICABLE_BY_RULE"


class ProductBoundary(StrEnum):
    AIR = "ACTIVATIVE_INTELLIGENCE_RUNTIME"
    AHP = "ATOMIC_HARNESS_PIPELINE"
    INTERVIEW = "INTERVIEW_EXPRESSION"
    STUDIO = "CONSCIOUS_ACTIVATIONS_STUDIO"
    VAE = "VISUAL_ASSET_EDITOR"
    DELEGATION = "DELEGATION_PROTOCOL"
    BUILDER = "ATOMIC_HARNESS_BUILDER"


class StopReason(StrEnum):
    QUALITY_THRESHOLD = "QUALITY_THRESHOLD"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    MAX_CANDIDATES = "MAX_CANDIDATES"
    PLATEAU = "PLATEAU"
    NO_ELIGIBLE_CANDIDATES = "NO_ELIGIBLE_CANDIDATES"
    MANUAL_STOP = "MANUAL_STOP"
