#!/usr/bin/env python3
"""Batch convert all book PDFs to Markdown with page boundary markers and manifests."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from pypdf import PdfReader

# Ensure UTF-8 output on Windows console
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def normalize(text: str) -> str:
    text = text.replace("\x00", "")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


def convert_pdf_to_md(src: Path, out: Path) -> dict:
    reader = PdfReader(str(src))
    pages = [normalize(page.extract_text() or "") for page in reader.pages]

    blocks = [
        f"# Source Conversion: {src.stem}",
        "",
        "> Generated by prepare_book_markdown.py logic. The original PDF remains authoritative.",
        "",
    ]
    nonempty_pages = 0
    for idx, page in enumerate(pages, start=1):
        blocks.append(f"<!-- PAGE {idx} -->")
        blocks.append(f"## Source Page {idx}")
        blocks.append(page or "[EMPTY EXTRACTION — VERIFY SOURCE PAGE]")
        blocks.append("")
        if page:
            nonempty_pages += 1

    out.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")

    manifest = {
        "source_pdf": str(src),
        "source_sha256": sha256(src),
        "markdown_output": str(out),
        "converter": "pypdf",
        "page_count": len(pages),
        "nonempty_extractions": nonempty_pages,
        "empty_extraction_pages": [i for i, p in enumerate(pages, start=1) if not p],
        "complete_read_requires_manual_verification": True,
    }
    manifest_path = out.with_suffix(out.suffix + ".conversion.json")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def main():
    bundle_dir = Path(__file__).resolve().parents[1]
    pdf_dir = bundle_dir / "Interview Questions Audit"
    out_dir = bundle_dir / "books_markdown"
    out_dir.mkdir(parents=True, exist_ok=True)

    pdf_files = sorted(list(pdf_dir.glob("*.pdf")))
    print(f"Converting {len(pdf_files)} PDF books in {pdf_dir}...", flush=True)

    summary = []
    for idx, src in enumerate(pdf_files, start=1):
        out = out_dir / f"{src.stem}.md"
        print(f"[{idx}/{len(pdf_files)}] Converting {src.name} -> {out.name}...", flush=True)
        try:
            manifest = convert_pdf_to_md(src, out)
            mb = out.stat().st_size / (1024 * 1024)
            print(
                f"  [OK] Finished {src.name}: {manifest['page_count']} pages "
                f"({manifest['nonempty_extractions']} non-empty), output: {mb:.2f} MB",
                flush=True,
            )
            summary.append((src.name, "SUCCESS", manifest["page_count"], mb))
        except Exception as e:
            print(f"  [FAIL] Failed {src.name}: {e}", flush=True)
            summary.append((src.name, "FAILED", 0, 0))

    print("\n--- BATCH CONVERSION SUMMARY ---", flush=True)
    for name, status, pages, mb in summary:
        print(f"{status:8} | {pages:4} pages | {mb:6.2f} MB | {name}", flush=True)


if __name__ == "__main__":
    main()
