#!/usr/bin/env python3
"""Convert a book PDF to Markdown for CAE source auditing.

The original PDF remains authoritative. This script creates a processing copy
with explicit page markers and a conversion manifest so auditors can verify
continuity. It does not OCR by default.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def normalize(text: str) -> str:
    text = text.replace("\x00", "")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


def extract_with_pypdf(path: Path) -> list[str]:
    from pypdf import PdfReader  # type: ignore
    reader = PdfReader(str(path))
    return [normalize(page.extract_text() or "") for page in reader.pages]


def extract_with_pdftotext(path: Path) -> list[str]:
    import subprocess
    proc = subprocess.run(
        ["pdftotext", "-layout", "-enc", "UTF-8", str(path), "-"],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or "pdftotext failed")
    chunks = re.split(r"\f", proc.stdout)
    return [normalize(c) for c in chunks]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()

    src = args.input.expanduser().resolve()
    out = args.output.expanduser().resolve()
    if not src.exists():
        print(f"SOURCE_ACCESS_FAILURE: {src} does not exist", file=sys.stderr)
        return 2
    if out.exists() and not args.overwrite:
        print(f"Refusing to overwrite existing output: {out}", file=sys.stderr)
        return 3

    pages: list[str]
    engine = None
    try:
        pages = extract_with_pypdf(src)
        engine = "pypdf"
    except Exception as exc:
        try:
            pages = extract_with_pdftotext(src)
            engine = "pdftotext"
        except Exception as exc2:
            print(
                "PDF_TO_MD_FAILURE: neither pypdf nor pdftotext could extract the source. "
                f"pypdf={exc!r}; pdftotext={exc2!r}",
                file=sys.stderr,
            )
            return 4

    out.parent.mkdir(parents=True, exist_ok=True)
    blocks = [f"# Source Conversion: {src.stem}", "", "> Generated by `prepare_book_markdown.py`. The original PDF remains authoritative.", ""]
    nonempty_pages = 0
    for idx, page in enumerate(pages, start=1):
        blocks.append(f"<!-- PAGE {idx} -->")
        blocks.append(f"## Source Page {idx}")
        blocks.append(page or "[EMPTY EXTRACTION — VERIFY SOURCE PAGE]")
        blocks.append("")
        if page:
            nonempty_pages += 1
    out.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")

    manifest = {
        "source_pdf": str(src),
        "source_sha256": sha256(src),
        "markdown_output": str(out),
        "converter": engine,
        "page_count": len(pages),
        "nonempty_extractions": nonempty_pages,
        "empty_extraction_pages": [i for i, p in enumerate(pages, start=1) if not p],
        "complete_read_requires_manual_verification": True,
    }
    manifest_path = out.with_suffix(out.suffix + ".conversion.json")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
