import type { ControlTowerProjection } from "./domain.js";

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

function badge(value: string): string {
  return `<span class="badge">${escapeHtml(value)}</span>`;
}

export function renderControlTowerHtml(projection: ControlTowerProjection): string {
  const nodes = projection.run_nodes.map((node) => `<tr><td>${escapeHtml(node.title)}</td><td>${badge(node.status)}</td><td>${escapeHtml(node.owner_product)}</td><td>${escapeHtml(node.dependency_ids.join(", ") || "—")}</td></tr>`).join("");
  const artifacts = projection.artifacts.map((artifact) => `<li><strong>${escapeHtml(artifact.artifact_kind)}</strong><span>${escapeHtml(artifact.uri)}</span><code>${artifact.sha256.slice(0, 16)}…</code></li>`).join("");
  const health = projection.runtime_health.map((item) => `<li><strong>${escapeHtml(item.component_id)}</strong>${badge(item.status)}<span>${item.budget_units_used}/${item.budget_units_limit} units</span></li>`).join("");
  const timeline = projection.timeline
    ? `<div class="timeline">${projection.timeline.tracks.map((track) => `<section><h4>${escapeHtml(track.role)}</h4>${track.item_ids.map((id) => `<span class="clip">${escapeHtml(id)}</span>`).join("")}</section>`).join("")}</div>`
    : `<p class="muted">No timeline projection for this campaign.</p>`;
  const exceptions = projection.exception_packages.length
    ? projection.exception_packages.map((item) => `<article class="exception"><strong>${escapeHtml(item.exception_code)}</strong><p>${escapeHtml(item.summary)}</p></article>`).join("")
    : `<p class="muted">No unresolved exceptions.</p>`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Conscious Activations Studio — ${escapeHtml(projection.order.project_id)}</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#17233c;background:#eef2f7}*{box-sizing:border-box}body{margin:0}.shell{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.rail{background:#17233c;color:#fff;padding:28px 20px}.rail h1{font-size:20px;margin:0 0 10px}.rail p{color:#b7c1d5;font-size:13px}.rail nav a{display:block;color:#dbe4f4;text-decoration:none;padding:9px 0}.main{padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.top h2{margin:0;font-size:28px}.muted{color:#6b7485}.badge{display:inline-block;background:#dbe7ff;border-radius:999px;padding:4px 9px;font-size:11px;font-weight:700;margin-right:5px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px;margin-top:18px}.card{background:#fff;border:1px solid #dbe1eb;border-radius:14px;padding:18px;box-shadow:0 4px 16px rgba(23,35,60,.05)}.span4{grid-column:span 4}.span6{grid-column:span 6}.span8{grid-column:span 8}.span12{grid-column:span 12}h3{margin:0 0 12px;font-size:16px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #e9edf3}ul{list-style:none;padding:0;margin:0}li{display:flex;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid #edf0f5}li span{flex:1}.timeline section{display:flex;gap:8px;align-items:center;margin:9px 0}.timeline h4{width:170px;margin:0;font-size:12px}.clip{background:#e6ecf8;border:1px solid #c7d4ea;border-radius:6px;padding:7px 9px;font-size:11px}.exception{background:#fff2e2;border-left:4px solid #ef9b3f;padding:10px 12px;border-radius:7px}.exception p{margin:6px 0 0}@media(max-width:900px){.shell{grid-template-columns:1fr}.rail{display:none}.span4,.span6,.span8{grid-column:span 12}}
</style></head><body><div class="shell"><aside class="rail"><h1>Conscious Activations</h1><p>Supervisory Studio · Phase 7 development surface</p><nav><a href="#campaign">Campaign</a><a href="#graph">Run graph</a><a href="#artifacts">Artifacts</a><a href="#timeline">Timeline</a><a href="#evidence">Evidence</a></nav></aside><main class="main"><header class="top"><div><p class="muted">${escapeHtml(projection.order.workspace_id)} / ${escapeHtml(projection.order.project_id)}</p><h2>${escapeHtml(projection.order.objective)}</h2><p>${badge(projection.campaign.lifecycle_state)}${badge(projection.campaign.autonomy_mode)}${badge(projection.studio_binding.primary_surface)}</p></div><div><strong>Projection</strong><br><code>${projection.projection_sha256.slice(0, 20)}…</code></div></header><section class="grid"><article id="campaign" class="card span4"><h3>Source package</h3><p><code>${escapeHtml(projection.source_package_ref.object_id)}</code></p><p class="muted">Harness ${escapeHtml(projection.order.harness_ref.object_id)}</p></article><article class="card span4"><h3>Semantic program</h3><p>${projection.semantic_production_package_ref ? `<code>${escapeHtml(projection.semantic_production_package_ref.object_id)}</code>` : "Not available"}</p><p class="muted">Final Script ${projection.final_script_ref ? "available" : "pending"}</p></article><article class="card span4"><h3>Actions</h3><p>${projection.available_actions.map(badge).join("")}</p></article><article id="graph" class="card span8"><h3>Source-to-batch run graph</h3><table><thead><tr><th>Node</th><th>Status</th><th>Owner</th><th>Depends on</th></tr></thead><tbody>${nodes}</tbody></table></article><article id="evidence" class="card span4"><h3>Runtime health</h3><ul>${health}</ul></article><article id="artifacts" class="card span6"><h3>Artifacts</h3><ul>${artifacts}</ul></article><article class="card span6"><h3>Exceptions</h3>${exceptions}</article><article id="timeline" class="card span12"><h3>Canonical timeline projection</h3>${timeline}</article></section></main></div></body></html>`;
}
